services:
  # builds APK file that can be installed on emulator or real device
  # apk stored in /app/build/outputs/apk/debug/app-debug.apk
  apk:
    build: .
    volumes:
      - .:/app
      - ./apk_output:/app/build/outputs/apk
    command: ./gradlew assembleDebug
